### ISSUE TITLE
Bind-Mount Recommendations Result In Error 

### ISSUE THREAD

**Issue by jonmchan** [cloudposse/bastion#17]
> Bind-mount /etc/passwd, /etc/shadow and /etc/group into the container as read-only

When attempting to do this, the docker container fails to startup. The error in the logs show as:

```
- Enabling SSH Audit Logs
chsh: failure while writing changes to /etc/passwd
```

This is because chsh is run on startup - https://github.com/cloudposse/bastion/blob/8411230e466decf3a069fa3a5185c94bd5028d75/rootfs/etc/init.d/ssh-audit#L13. 

The code should be updated to allow passwd, shadow, and group to not be modified during normal usage or the recommendation to keep those files mounted as read-only should be removed.

**Comment by osterman** [comment]
Yes, that's a good point.

**Comment by osterman** [comment]
This has been fixed in https://github.com/cloudposse/bastion/releases/tag/0.1.4
