### ISSUE TITLE
Duo Does work with latest build

### ISSUE THREAD

**Issue by mhwelsh** [cloudposse/bastion#34]
Thanks for doing this!  Was able to get Google auth set up fine, but eventually wanted to switch to Duo.

Looks like when the switch to multi-stage build was made, a bug was introduced.  The locations of the pamduo libs is not copied correctly from the builder image, so you get an error saying that module cannot be found for user root.

Put a patch together locally but github is flaky tonight.  The prefix command to duo pam doesn't do anything.  make install still puts the libs in /lib64/security.  This is not copied to the main image.

I added:
COPY --from=duo-builder lib64/ /lib/

after line 98.  This works.

**Comment by osterman** [comment]
@mhwelsh thanks so much for reporting this and your workaround. That made it quick for @alebabai to address the issue.
