### ISSUE TITLE
ansible fails on bastion

### ISSUE THREAD

**Issue by chathsuom** [cloudposse/bastion#48]
ansible executes below command and it fails at 9.shell exec command

ssh 172.21.2.54 '/bin/sh -c '"'"'echo "`pwd`" && sleep 0'"'"''

**Comment by chathsuom** [comment]
rabbitmq-staging [~]# k="/bin/sh -c 'echo "/root" && sleep 0'"
rabbitmq-staging [~]# exec ${k}
/root: line 1: syntax error: unterminated quoted string

**Comment by jonmchan** [comment]
We are closing out stale issues. If this is still an issue for you, please add a new issue. Thank you.
