### ISSUE TITLE
Documentation outdated. 

### ISSUE THREAD

**Issue by a-nldisr** [cloudposse/bastion#58]
```
The bastion does not attempt to manage user accounts. We suggest using GitHub Authorized Keys to provision user accounts and SSH keys. We provide a chart of how we recommend doing it.
```
The chart is offline, could anyone provide it?

**Comment by osterman** [comment]
Chart should not be offline - can you share details?

https://github.com/cloudposse/charts/tree/master/incubator/bastion

**Comment by a-nldisr** [comment]
Weird, when i clicked https://github.com/cloudposse/charts/tree/master/incubator/bastion i got a 404...
