### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by palves** [cloudposse/bastion#65]
Hi!

What is the status of this project?  I was looking around for an ssh jump host with 2FA support, and found this, which seemed perfect.  However, the project seems to have stalled in the last few years, and hasn't been kept up to date with Alpine, etc., even though there are pending pull requests in that direction.  It would make me uneasy to rely on old versions of sshd etc.

So, is this project no longer maintained?  Is there some alternative fork people are working on instead?

**Comment by osterman** [comment]
We have a new maintainer helping us out. @jonmchan has put in considerable T&E to update this to make it easier for us to continue to accept contributions moving forward. @max-lobur and @jonmchan have also added the GitHub Actions for automated testing.
