### ISSUE TITLE
Is bsd-compatible-realpath.patch still necessary?

### ISSUE THREAD

**Issue by jonmchan** [cloudposse/bastion#69]
I'm in the process of updating bastion to the latest versions of openssh and alpine. The latest version of openssh no longer use bsd-compatible-realpath: 

https://github.com/openssh/openssh-portable/commit/4efe1adf05ee5d3fce44320fcff68735891f4ee6#diff-3de5ce59178068d8ec777db567fd51314363b970126177774e0049f79b4337e5

Is the `patches/openssh/bsd-compatible-realpath.patch` still necessary?

@osterman @alebabai  ?

Thank you!

**Comment by max-lobur** [comment]
Yea I think we should remove it
