### ISSUE TITLE
make readme fails

### ISSUE THREAD

**Issue by jonmchan** [cloudposse/bastion#72]
Cannot regenerate the readme currently on my machine.

Ran:

```
make init
make readme/deps
make readme
```

This errors out with:

```
$ make readme
* Package gomplate already installed
make: gomplate: No such file or directory
make: *** [readme/build] Error 1
```

**Comment by Nuru** [comment]
Closing as duplicate of https://github.com/cloudposse/build-harness/issues/344 because that is the core issue.
